"""add contacts, disclosures, fund-scoped data, template chrome

Revision ID: 9088a57024dd
Revises: fd3a11d58d6b
Create Date: 2026-09-15 02:45:22.753411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9088a57024dd'
down_revision: Union[str, None] = 'fd3a11d58d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fund_data', sa.Column('ticker', sa.String(length=20), nullable=True))
    op.add_column('fund_data', sa.Column('inception_date', sa.Date(), nullable=True))
    op.add_column('fund_data', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('fund_data', sa.Column('investment_universe', sa.String(length=150), nullable=True))
    # batch mode: SQLite has no native ALTER COLUMN, so a nullability change
    # needs a table rebuild (same pattern as the 13e32ea4b5b4 migration).
    with op.batch_alter_table('holdings') as batch_op:
        batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=True)
    with op.batch_alter_table('performance_snapshots') as batch_op:
        batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=True)
    op.add_column('report_templates', sa.Column('disclosure_ids', sa.Text(), nullable=True))
    op.add_column('report_templates', sa.Column('header_config', sa.Text(), nullable=True))
    op.add_column('report_templates', sa.Column('footer_config', sa.Text(), nullable=True))
    with op.batch_alter_table('reports') as batch_op:
        batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports') as batch_op:
        batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('report_templates', 'footer_config')
    op.drop_column('report_templates', 'header_config')
    op.drop_column('report_templates', 'disclosure_ids')
    with op.batch_alter_table('performance_snapshots') as batch_op:
        batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=False)
    with op.batch_alter_table('holdings') as batch_op:
        batch_op.alter_column('client_id', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('fund_data', 'investment_universe')
    op.drop_column('fund_data', 'description')
    op.drop_column('fund_data', 'inception_date')
    op.drop_column('fund_data', 'ticker')
    op.drop_table('disclosures')
    op.drop_table('contacts')
    # ### end Alembic commands ###
