"""add theme config to report templates

Revision ID: a7c6c22cc60b
Revises: f1807d7ee3ec
Create Date: 2026-09-15 15:11:35.050420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c6c22cc60b'
down_revision: Union[str, None] = 'f1807d7ee3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_templates', sa.Column('theme_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_templates', 'theme_config')
    # ### end Alembic commands ###
