"""add component reviews and template client assignments

Revision ID: fc92269c93e6
Revises: a7c6c22cc60b
Create Date: 2026-09-15 15:51:20.643575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc92269c93e6'
down_revision: Union[str, None] = 'a7c6c22cc60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_client_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'client_id', name='uq_template_client_assignment')
    )
    op.create_table('component_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(length=64), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('report_templates', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('report_templates', sa.Column('approved_by', sa.Integer(), nullable=True))
    # batch mode: SQLite can't ALTER a table to add a constraint after the
    # fact (same pattern as the 9088a57024dd migration).
    with op.batch_alter_table('report_templates') as batch_op:
        batch_op.create_foreign_key('fk_report_templates_approved_by_users', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_templates') as batch_op:
        batch_op.drop_constraint('fk_report_templates_approved_by_users', type_='foreignkey')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')
    op.drop_table('component_reviews')
    op.drop_table('template_client_assignments')
    # ### end Alembic commands ###
