"""add report team and type

Revision ID: fd3a11d58d6b
Revises: 877f6a0406a5
Create Date: 2026-09-14 23:27:48.703766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3a11d58d6b'
down_revision: Union[str, None] = '877f6a0406a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('team', sa.String(length=60), nullable=True))
    op.add_column('reports', sa.Column('report_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'report_type')
    op.drop_column('reports', 'team')
    # ### end Alembic commands ###
